#!/usr/bin/env bash

repository=~/dotfiles

# Disable output for pushd
pushd () {
    command pushd "$@" > /dev/null
}

# Disable output for popd
popd () {
    command popd "$@" > /dev/null
}

home() {
  pushd $repository
  nix build .#homeManagerConfiguration.qwbarch.activationPackage
  ./result/activate
  popd
}

system() {
  pushd $repository
  sudo nixos-rebuild switch --flake .#
  popd
}

case $1 in
  "home")
    home;;
  "system")
    system;;
  *)
    system
    home;;
esac
